#!/usr/bin/env bash

usage() {
    echo "Usage: $(basename $0) REMOTE_DIR MOUNTPOINT"
}

if [[ "$#" -lt 2 ]]
then
    usage
    exit 2
fi

REMOTE=acd-crypt
REMOTE_DIR="$1"
MOUNTPOINT="$2"

# Check if rclone is installed, resort to docker if not
if command -v rclone >/dev/null 2>&1
then
    COMMAND=rclone
else
    # ?? --cap-add mknod ??
    COMMAND="docker run --cap-add=SYS_ADMIN --device=/dev/fuse --name rclone-${1} --user 0 --rm -v /srv/rclone/config:/config -v ${MOUNTPOINT}:/data:shared pschmitt/rclone"
fi

$COMMAND mount "${REMOTE}:${REMOTE_DIR}" /data
