#!/usr/bin/env bash

cd $(readlink -f $(dirname "$0"))

DEST_REMOTE=acd-crypt
DEFAULT_FILE_PATH=/mnt/data
RCLONE_CONFIG=$PWD/config/.rclone.conf

declare -A DEST_DIR_MAPPING
DEST_DIR_MAPPING[audio]='Audio'
DEST_DIR_MAPPING[backup]='Backup'
DEST_DIR_MAPPING[docs]='Documents'
DEST_DIR_MAPPING[videos]='Videos'
DEST_DIR_MAPPING[pictures]='Pictures/Pictures'
DEST_DIR_MAPPING[gphotos]='Pictures/Google Photos'
# DEST_DIR_MAPPING[test]='TEST-DELETEME'

declare -A SRC_DIR_MAPPING
SRC_DIR_MAPPING[gphotos]='gdrive:Google Photos'
# SRC_DIR_MAPPING[test]='/tmp/source'

usage() {
    echo "Usage: $(basename $0) [-n] DIR [DEST]"
}

if [[ "$#" -lt 1 || -z "$1" ]]
then
    usage
    exit 2
fi

# Check whether -n was set
case "$1" in
    -n|--no-deletions)
        NO_DELETION=1
        shift
        ;;
esac

# If the user supplies the path to the src dir, use it
if [[ -d "$1" ]]
then
    SRC_DIR="$1"
# Check if there is a mapping for the provided dir
elif [[ -n "${SRC_DIR_MAPPING[$1]}" ]]
then
    SRC_DIR="${SRC_DIR_MAPPING[$1]}"
else
# Default to /mnt/data/XX
    SRC_DIR="${DEFAULT_FILE_PATH}/${1}"
fi

# If the user supplies a dest dir, use it
if [[ -n "$2" ]]
then
    DEST_DIR="$2"
else
    DEST_DIR="${DEST_DIR_MAPPING[$1]}"
fi

# Uppercase the first letter if DEST_DIR was not set by the user and has no mapping
if [[ -z "$DEST_DIR" ]]
then
    DEST_DIR="$(tr '[:lower:]' '[:upper:]' <<< ${1:0:1})${1:1}"
fi

# Check if rclone is installed, resort to docker if not
if command -v rclone >/dev/null 2>&1
then
    COMMAND="rclone --config $RCLONE_CONFIG"
else
    if grep "$DEFAULT_FILE_PATH" <<< "$SRC_DIR" > /dev/null 2>&1
    then
        # Optional volume mount in case we want to sync a local dir
        VOLUME="-v $SRC_DIR:$SRC_DIR"
    fi
    COMMAND="docker run --name rclone-${1} --user 0 --rm -v ${RCLONE_CONFIG}:/config/.rclone.conf $VOLUME pschmitt/rclone"
fi

if [[ -n "$NO_DELETION" ]]
then
    RCLONE_SUBCOMMAND=copy
else
    RCLONE_SUBCOMMAND=sync
fi

echo Execute $COMMAND "$RCLONE_SUBCOMMAND" --max-size 30G "$SRC_DIR" "$DEST_REMOTE:${DEST_DIR}"
$COMMAND "$RCLONE_SUBCOMMAND" --max-size 30G "$SRC_DIR" "$DEST_REMOTE:${DEST_DIR}"
